keycap-archivist/website

- package.json
- src/assets/scss/style.scss
- src/components/layout.js
- src/layouts/maker.js
- src/layouts/sculpt.js
- yarn.lock
> feat: add colorway anchors

- src/assets/css/base.css
- src/assets/scss/style.scss
- src/layouts/maker.js
- src/layouts/sculpt.js
- src/pages/index.js
- card layout updates
- trying to wrangle all of the various image dimensions
> Ui cleanup

- gatsby-node.js
- package.json
- src/layouts/maker.js
Reduce the page load from 230Mb to 3Mb lmao
> fix: performance issues

- src/assets/scss/style.scss
- src/layouts/sculpt.js
Fix the issue with `:target` because when the connection is slow it does not catch.
Also added the redirect of the hash on the copy of the link of the cap to highlight is directly and not being silently copied in the clipboard.
> fix: highlight of keycap

- gatsby-config.js
- gatsby-node.js
- package.json
- src/components/seo.js
- yarn.lock
Moving to `gatsby-plugin-next-seo` as it embeds `react-helmet-async` which is a fork more maintained than the previous one we used.
Also now the html files are generated, this line was missing:
https://github.com/keycap-archivist/website/compare/fix_seo?expand=1#diff-fda05457e393bada716f508859bfc604R82
> fix: seo rendering

- gatsby-node.js
- src/components/header.js
- src/layouts/cw.js
- src/layouts/sculpt.js
@nchristus so i tried make all the colorway pages and it works, the only problem it's a bit slow, so there is a condition based on an env variable in the config:
https://github.com/keycap-archivist/website/compare/add_colorway_pages?expand=1#diff-fda05457e393bada716f508859bfc604R66
The colorway page needs some of your skills also :)
If you can help me on this it would be great. As now we will have a dedicated page for each colorway and we can have the proper open graph for it.
> feat: add colorway pages

- src/assets/css/base.css
- src/assets/scss/style.scss
- src/components/header.js
- src/components/search.js
> make_smart_search: updated search styles

- src/assets/css/base.css
- src/assets/scss/style.scss
- src/components/header.js
- src/components/search.js
The search was limiting the results of sculpts and artist because of too much colorways in the results. Now the limit is only applied on colorway results.
Also minor fix on search result UI. Need your expertise on it @nchristus
> fix: maker smarter search

- src/components/thumbnail-image.js
- src/layouts/maker.js
- src/layouts/sculpt.js
improve resize of images coming from google cdn
> feat: Improve img perf

- src/components/search.js
Using `QuickScore` only to determine the search and we extrapolate sculpts and artists from the results.
Also improve a bit the performance and the size of `page_data.json`
> feat: make smarter search

- src/pages/about.js
- yarn.lock
- ui cleanup
- small text changes
> add_about: cleaned up UI a bit, some small text changes

- src/components/header.js
- src/pages/about.js
- yarn.lock
Adding the about section. This needs to be reviewed by and english native person. Also maybe some UI polishing may be needed :)
> feat: Add about section

- gatsby-config.js
- gatsby-node.js
- package.json
- src/assets/css/base.css
- src/assets/scss/style.scss
- src/components/header.js
- src/content/blog/1-hello-world.md
- src/content/blog/2-coz-itw.md
- src/layouts/blog-post.js
- src/pages/blog.js
- yarn.lock
> feat: add blog

- src/layouts/sculpt.js
Added favorite star functionality, reworked links in sculpt component
> Add favorite

- src/components/modals/submit-new-cw.js
- src/layouts/sculpt.js
Added submit new colorway button to sculpt component. When pressed a modal opens allowing the user to upload a file and submit a colorway name.
Created a new branch because in first submit new cw branch old commits were mixed in.
> Submit new cw 2

- src/internal/wishlist.js
- src/layouts/blog-post.js
- src/layouts/sculpt.js
- src/pages/about.js
- src/pages/blog.js
- src/pages/wishlist.js
This PR to resolve issue #60 
**Done**:
**Preview**:
> Wishlist v2

- src/layouts/maker.js
Here is a screen of the render:
> Add in maker layout website and instagram link when it exists

- src/pages/wishlist.js
It works better with a link ;) (href, download are attributes for `a` tag)
> Use a link for the download button

- src/assets/scss/style.scss
- src/layouts/cw.js
> feat: set cw-thumbnail at min-width 25vh

- src/assets/scss/style.scss
- src/layouts/cw.js
> Sculpt colorway fix

- src/layouts/cw.js
- src/layouts/sculpt.js
> Add wishlist and trade list limit

- src/internal/collection.js
- src/internal/wishlist.js
- src/layouts/base.js
- src/pages/config.js
> Sync between cloud and local storage

- src/pages/wishlist.js
fix wishlist generation stuck in case of validation error.
Also prompts the error and the json generated for easier debugging. Still not viable in the long term.
> fix: wishlist bug

- gatsby-node.js
- src/internal/favorite.js
- src/pages/index.js
Add/remove a maker to favorite list and put it on top. So you can access it quickly
> Favorite makers

- src/pages/index.js
- on production site using SSG there is an issue with the pregenerated
rendered code not having access to local storage. Trigger an update
of the favorite maker's list using a useEffect hook, after page has
loaded to fix this.
> Potential Fix for Favorite Makers

- src/pages-dynamic/sculpt.js
Found by accident playing around :)
> Fixed variable for releaseDate

- src/components/modal.js
- src/components/modals/confirm-dialog.js
User reported light theme issues
Updated modal background color
> Update styles for lightmode visibility

- package.json
- yarn.lock
Reverts keycap-archivist/website#375
> Revert "Bump tailwindcss from 2.2.9 to 3.3.2"

- gatsby-config.js
- gatsby-node.js
- package.json
- pnpm-lock.yaml
- Moving Tailwind 3 out of `devDependencies` to fix dak theme in production.
- Minor linting issues in gatsby files.
> fix: fixing dependencies and minor linting issues

- package.json
- pnpm-lock.yaml
- src/components/header.js
- src/pages/config.js
- src/pages/wishlist.js
- Fixing minor issues for deployment (again).
> fix: fixing dependencies and minor ui issues

- src/components/acBanner.js
- src/components/header.js
- src/pages-dynamic/sculpt.js
- src/pages/index.js
- Added wrapper buttons around clickable SVG elements.
- Made them easier to click on mobile.
> fix/a11y-buttons: larger buttons for mobiles

- src/pages/wishlist.js
- Added lost tradelists configuration during the UI update.
> fix/tradelists : adding back tradelists configuration

- src/pages-dynamic/colorway.js
- Fixed desktop and mobile interactions for colorway pages.
> fix: colorway interactions for mobile & desktop
